spring:
  cloud:
    azure:
      eventhubs:
        ##SEvent Hubs Namespace
        namespace: event-hub-demo
    stream:
      bindings:
        producer-out-0:
          ##Event Hubs Instance
          destination: event-hub-demo
      function:
        definition: producer;