spring:
  cloud:
    azure:
      eventhubs:
        ##Valor del espacio de nombres de Event Hubs
        namespace: ${AZURE_EVENTHUBS_NAMESPACE}
    stream:
      bindings:
        supply-out-0:
          destination: ${AZURE_EVENTHUB_NAME}
      function:
        definition: supply;